==== 1.1.3 Converter

User can define a custom Converter between a custom defined type (or a simple different type from the one defined on table column) and table column referenced by *@Column* annotation using an implementation of *ValueConverter<T,R>* where *T* is the table column type and *R* is the custom defined type

Jaorm contains two custom implementation for Boolean type :

- BooleanStringConverter, that convert a matching "Y" string to true , otherwise to false
- BooleanIntConverter, that convert 1 to true, otherwise to false

Each of them contains standard implementation for ValueConverter with a public static instance (aka Singleton) named *INSTANCE*.

[source,java]
----
public class BooleanIntConverter implements ValueConverter<Integer, Boolean> {

    public static final BooleanIntConverter INSTANCE = new BooleanIntConverter();

    private BooleanIntConverter() {}

    @Override
    public Boolean fromSql(Integer val) {
        return val != null && val == 1;
    }

    @Override
    public Integer toSql(Boolean val) {
        return val != null && val ? 1 : 0;
    }
}
----

[TIP]
====
User can follow standard implementation (defining a public *INSTANCE* field) or defining a public constructor
====
