== 2 DSL

DSL Module is an abstraction over simple SQL Queries using a DSL.

It can be combined with Query annotated implementation or used in a stand-alone class.

=== 2.1 Query Builder

*QueryBuilder* is the entry-point for create custom query and can be used for create complete queries with *where*, *join*, *order* and *limit/offset* clause

[source,java]
----
    QueryBuilder.select(MyEntity.class)
                    .join(MyEntityJoin.class, "A")
                        .on(COL_4).eq(COL_2)
                        .on(COL_3).eq(COL_1).orOn(COL_4).ne(COL_2)
                    .where(COL_1).eq(1)
                    .andWhere(COL_3, "A").ne(2)
                    .read();
----

User can define a custom *QueryConfig* or use standard implementation with *select(Class<T>)* method

*QueryBuilder* will produce :

- A *java.util.Optional<T>*, for an optional result, using readOpt method
- A *java.util.List<T>*, for a list of result, using readAll method
- An *Entity* instance , for a single result, using read method

[TIP]
====
Input Class in select methods must be a valid *Entity* or Jaorm will throw a Runtime Exception
====

==== 2.1.1 Entity Columns

Processor check if DSL is present in the classpath during processing annotation phase and create custom <EntityName>Columns class that contains constant defined columns used for type-safety building for *where*, *join* and *order by* clause

[source,java]
----
public final class UserColumns {
    public static final SqlColumn<User, Integer> USER_ID = SqlColumn.instance(User.class, "USER_ID", Integer.class);

    public static final SqlColumn<User, Integer> DEPARTMENT_ID = SqlColumn.instance(User.class, "DEPARTMENT_ID", Integer.class);

    public static final SqlColumn<User, String> USER_NAME = SqlColumn.instance(User.class, "USER_NAME", String.class);
}
----

include::query-config/index.adoc[]
include::where/index.adoc[]
include::join/index.adoc[]
include::order/index.adoc[]
include::limit-offset/index.adoc[]
