=== 1.3 Query Processor

For each interface that contains a method with **@Query** annotation or is annotated with **@Dao** annotation, an implementation is generated.

Implemented Method execute sql value in the annotation and return an object for a non-void method. If returned Object is an Entity ,
Core module create the mapped entity else the first column is returned.

TIP: Custom runtime mapper are also supported with the use of *TableRow* return type.

Query supports different arguments matchers likes :

- Standard Wildcards
- A named parameter (es :name)
- Ordered Wildcards (es: ?1,?2)
- At Names (es: @name, @name2)
- No Args (**@Query.noArgs** must be set to true for this special case)

Query uses parameter name or annotated parameter with Param for retrieve the current value during compile-time

[source,java]
----
public interface UserDao extends BaseDao<User> {

    @Query(sql = "SELECT * FROM USER WHERE USER_ID = ? AND USERNAME = ?")
    User getUser(String userId, String username);

    @Query(sql = "SELECT * FROM USER WHERE USER_ID = ? AND USERNAME = ?")
    Optional<User> getUserOpt(String userId, String username);

    @Query(sql = "SELECT * FROM USER WHERE USER_ID = ? AND USERNAME = ?")
    List<User> getAllUsers(String userId, String username);

    @Query(sql = "SELECT * FROM USER WHERE USER_ID = :userId
        AND USERNAME = :username AND NAME = :username")
    User getUserNamed(String userId, String username);

    @Query(sql = "SELECT * FROM USER WHERE USER_ID = :userId
        AND USERNAME = :username AND NAME = :username")
    User getUserNamed2(String userId, @Param(name = "USERNAME") String name);

    @Query(sql = "SELECT * FROM USER WHERE USER_ID = ?1 AND USERNAME = ?2 AND NAME = ?1")
    User getUserOrdered(String userId, String username);

    @Query(sql = "SELECT * FROM USER WHERE USER_ID = @userId
        AND USERNAME = @username AND NAME = @username")
    User getUserAtNamed(String userId, String username);

    @Query(sql = "SELECT * FROM USER WHERE USER_ID = @userId
        AND USERNAME = @username AND NAME = @username")
    TableRow getUserTableRow(String userId, String username);

    @Query(sql = "SELECT * FROM USER WHERE USER_ID = @userId
        AND USERNAME = @username AND NAME = @username")
    Optional<TableRow> getUserTableRowOpt(String userId, String username);

    @Query(sql = "SELECT * FROM USER WHERE USER_ID = @userId
        AND USERNAME = @username AND NAME = @username")
    Stream<TableRow> getUserTableRowStream(String userId, String username);

    @Query(sql = "UPDATE USER SET USER_ID = :userId where USERNAME = :username")
    void updateUser(String userId, String username);

    @Query(sql = "DELETE FROM USER", noArgs = true)
    void deleteAll();
}
----

Annotations on an interface with **@Query** methods or **@Dao** annotation are also propagated in the implementation

[source,java]
----
@Dao
@RequestScoped
public interface MyDao extends BaseDao<User> {}

@RequestScoped
public class MyDaoImpl implements MyDao {} // @RequestScoped is propagated
----

[TIP]
====
User can also use custom types that can be converted to sql types if the converter is already used on an *Entity*
====

==== 1.2.1 Supported Return Type

Custom generated Queries supports return types like :

- *Void*, for Update/Delete SQL
- *Optional<T>*, for an optional entity/projection
- *Optional<TableRow>*, for an optional mappable row
- *List<T>*, for a collection of entities/projections
- *Stream<T>*, for a stream of entities/projections
- *Stream<TableRow>*, for a stream of mappable rows
- *TableRow*, for a mappable row
- *T*, for an entity or a projection or a supported accessible type

==== 1.2.2 Fast Table Read

User can also use generated **Tables** entry point for type-safe read of an Entity.

**Tables** use a custom DSL for retrieve each Entity annotated with **Table**

[source,java]
----
public class Test {

  public static void main(String... args) {
    User user = Tables.USER_TABLE.userId(10).read();
  }
}
----

==== 1.2.3 SQL in File

User can also use stored SQL located in resources.

TIP: Jaorm will read and replace SQL location with full text during compile phase before validation.

[source,java]
----
@Dao
public interface CustomUserDao {

    @Query(sql = "/mySql.sql")
    Optional<User> getUserOpt(int userId);
}
----
